In [2]:
import numpy as np

In [ ]:
#Random Array in Numpy Uniformly destributed
arr=np.random.rand(1,4)

In [ ]:
print(arr)

[[0.60885767 0.58869534 0.73736611 0.1950989 ]]


In [ ]:
#Random Array In Numpy normal distributed
arr=np.random.randn(1,4)
print(arr)

[[ 0.80745053 -0.92573509 -1.12139786  0.39328523]]


In [ ]:
#Numpy-Input to below function is (start,stop,number of elements)
arr=np.random.randint(1,10,size=4)
print(arr)

[8 5 5 8]


In [ ]:
arr=np.random.random_integers

NameError: name 'np' is not defined

In [ ]:
arr=np.array([1,2.3,3])

In [ ]:
print(arr)

[1.  2.3 3. ]


In [ ]:
lst=["priya","sneha","vaishu"]

In [ ]:
arr=np.array(lst)
print(arr)

['priya' 'sneha' 'vaishu']


In [ ]:
#Creating array with different datatypes

In [ ]:
arr=np.array([1,2,2],np.float64)
arr

array([1., 2., 2.])

In [ ]:
arr=np.array([1,2.,22],np.int64)

In [ ]:
arr

array([ 1,  2, 22])

In [4]:
#Type casting one array to another
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr2=np.astype(arr,np.float64)

In [ ]:
arr2

array([1., 2., 3.])

In [6]:
print(arr2.shape)

(3,)


In [7]:
arr2.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [9]:
arr=np.array([1,2,3,4,5,6])

In [10]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#Ravel is used to convert any particular array to 1D Array
arr=np.array([[1,2,2],
             [2,2,2]])

In [13]:
arr.ravel

<function ndarray.ravel>

In [14]:
print(arr.ravel)

<built-in method ravel of numpy.ndarray object at 0x786a0b730c30>


In [15]:
ravel=arr.ravel()

In [16]:
print(ravel)

[1 2 2 2 2 2]


In [17]:
print(arr)

[[1 2 2]
 [2 2 2]]


In [20]:
#Flatten
flatton=arr.flatten()
print(flatton)

[1 2 2 2 2 2]


In [21]:
#Arithmetic

In [22]:
arr1=np.array([1,2,3])

In [23]:
arr2=np.array([2,4,6])

In [24]:
print(arr1+arr2)

[3 6 9]


In [26]:
print(arr1-arr2)

[-1 -2 -3]


In [27]:
print(arr1/arr2)

[0.5 0.5 0.5]


In [28]:
print(arr1*arr2)

[ 2  8 18]


In [29]:
print(arr1//arr2)

[0 0 0]
