In [ ]:
import numpy as np

In [ ]:
#Random Array in Numpy Uniformly destributed
arr=np.random.rand(1,4)

In [ ]:
print(arr)

[[0.60885767 0.58869534 0.73736611 0.1950989 ]]


In [ ]:
#Random Array In Numpy normal distributed
arr=np.random.randn(1,4)
print(arr)

[[ 0.80745053 -0.92573509 -1.12139786  0.39328523]]


In [ ]:
#Numpy-Input to below function is (start,stop,number of elements)
arr=np.random.randint(1,10,size=4)
print(arr)

[8 5 5 8]


In [ ]:
arr=np.random.random_integers

NameError: name 'np' is not defined

In [ ]:
arr=np.array([1,2.3,3])

In [ ]:
print(arr)

[1.  2.3 3. ]


In [ ]:
lst=["priya","sneha","vaishu"]

In [ ]:
arr=np.array(lst)
print(arr)

['priya' 'sneha' 'vaishu']


In [ ]:
#Creating array with different datatypes

In [ ]:
arr=np.array([1,2,2],np.float64)
arr

array([1., 2., 2.])

In [ ]:
arr=np.array([1,2.,22],np.int64)

In [ ]:
arr

array([ 1,  2, 22])

In [ ]:
#Type casting one array to another
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr2=np.astype(arr,np.float64)

In [ ]:
arr2

array([1., 2., 3.])

In [ ]:
print(arr2.shape)

(3,)


In [ ]:
arr2.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Ravel is used to convert any particular array to 1D Array
arr=np.array([[1,2,2],
             [2,2,2]])

In [ ]:
arr.ravel

<function ndarray.ravel>

In [ ]:
print(arr.ravel)

<built-in method ravel of numpy.ndarray object at 0x786a0b730c30>


In [ ]:
ravel=arr.ravel()

In [ ]:
print(ravel)

[1 2 2 2 2 2]


In [ ]:
print(arr)

[[1 2 2]
 [2 2 2]]


In [ ]:
#Flatten
flatton=arr.flatten()
print(flatton)

[1 2 2 2 2 2]


In [ ]:
#Arithmetic

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([2,4,6])

In [ ]:
print(arr1+arr2)

[3 6 9]


In [ ]:
print(arr1-arr2)

[-1 -2 -3]


In [ ]:
print(arr1/arr2)

[0.5 0.5 0.5]


In [ ]:
print(arr1*arr2)

[ 2  8 18]


In [ ]:
print(arr1//arr2)

[0 0 0]


In [ ]:
arr=[2,3,4]

In [ ]:
arr[0,1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
#Array Slice
arr[0:1]

[2]

In [ ]:
arr=[2,4,6,8,20,35,66]

In [ ]:
arr[1:4:2]

[4, 8]

In [ ]:
#Multidimensinal Slicing
arr=np.array([[2,4,6],
     [4,7,8],
     [22,12,2]])

In [ ]:
arr[0:3]

[[2, 4, 6], [4, 7, 8], [22, 12, 2]]

In [ ]:
arr[0:2]

[[2, 4, 6], [4, 7, 8]]

In [ ]:
arr[0:2:2]

[[2, 4, 6]]

In [ ]:
#Transpose of matrix
print(arr.transpose())

[[ 2  4 22]
 [ 4  7 12]
 [ 6  8  2]]


In [ ]:
#Concatination of numpy arrays combine 2 arrays
a=np.array([1,2,3])
b=np.array([4,5,6])


In [ ]:
combine=np.concatenate((a,b))

In [ ]:
print(combine)

[1 2 3 4 5 6]


In [ ]:
#Hstack
hstackArray=np.hstack((a,b))

In [ ]:
print(hstackArray)

[1 2 3 4 5 6]


In [ ]:
#Vstack
vstackArray=np.vstack((a,b))
vstackArray

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Here zero means vertical axis
stackArray=np.stack((a,b),axis=0)
print(stackArray)



[[1 2 3]
 [4 5 6]]


In [ ]:
stackArray=np.stack((a,b),axis=1)

In [ ]:
stackArray


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#Spiliting
arr1=np.array([[1,2,3],[4,4,5]])

In [ ]:
#vspilit
vspilitArray=np.vsplit(arr1,2)

In [ ]:
print(vspilitArray)

[array([[1, 2, 3]]), array([[4, 4, 5]])]


In [ ]:
#Hspilit array
hspilitArray=np.hsplit(arr1,2)
hspilitArray

ValueError: array split does not result in an equal division

In [ ]:
#Condition based choices
#Where

In [ ]:
arr=np.array([1,2,3])
result=np.where(arr<2,"low","high")

In [ ]:
print(result)

['low' 'high' 'high']


In [ ]:
#ArgWhere gives row column position for given array where the condition is staisfied
print(np.argwhere(arr>2))

[[2]]


In [ ]:
mask=np.logical_and(arr>2,arr<5)
print(mask)

[False False  True]


In [ ]:
print(np.argwhere(arr>3))

[[0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]]


In [ ]:
#Masking Array
mask=np.logical_or(arr1>2,arr1>9)
print(mask)

[False False  True]


In [ ]:
arr1[mask]

array([3])

In [ ]:
#BroadCasting
image=np.array([[2,1,6],[8,4,6]])

In [ ]:
print(image)

[[2 1 6]
 [8 4 6]]


In [ ]:
brightness=image+50

In [ ]:
print(brightness)

[[52 51 56]
 [58 54 56]]


In [ ]:
#Vectorization
def square(x):
    return x*x

vSquare=np.vectorize(square)

array=np.array([2,3,4])

arr2=vSquare(array)

print(arr2)

[ 4  9 16]


In [ ]:
#How to deal with missing values
a=np.array([2,4,np.nan])

In [ ]:
print(a)

[ 2.  4. nan]


In [ ]:
#np.isnan
#np.isinf
#np.isfinfite

#This are going to be used when you have to check wheather your array contains nan or infinite or finite values
print(np.isnan(a))


[False False  True]


In [ ]:
b=np.array([1,2,np.inf,np.nan])

In [ ]:
print(np.isnan(b))

[False False False  True]


In [ ]:
print(np.logical_or(np.isnan(b),np.isinf(b)))

[False False  True  True]


In [ ]:
#after finding null how to replace that values

new_b=np.nan_to_num(b)

In [ ]:
print(new_b)

[1.00000000e+000 2.00000000e+000 1.79769313e+308 0.00000000e+000]
