In [4]:
import numpy as np

In [5]:
a=np.array([2,3,4])

In [6]:
a.ndim #N dim returns the dimention of numpy array

1

In [17]:
#np arrange help use to create an array based on start stop and increment
arr=np.arange(2,11,2)

In [15]:
print(arr)

[ 2  4  6  8 10]


In [26]:
#linspace helps us to create evenly spaced numpy array
linsSpaceNumpyarray=np.linspace(2,10,2)

In [27]:
print(linsSpaceNumpyarray)

[ 2. 10.]


In [32]:
#Logs space helps us to create power array
np.logspace(0,2,6)

array([  1.        ,   2.51188643,   6.30957344,  15.84893192,
        39.81071706, 100.        ])

In [34]:
#zeros array create arays of 0
arr=np.zeros(8)

In [35]:
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
#Ones array
arr=np.ones(9)

In [38]:
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [39]:
#array of numbers of user choice
arr=np.full(8,5)

In [40]:
print(arr)

[5 5 5 5 5 5 5 5]


In [42]:
arr=np.empty(2)
print(arr)

[  1. 100.]
