In [ ]:
import numpy as np

In [ ]:
#Random Array in Numpy Uniformly destributed
arr=np.random.rand(1,4)

In [ ]:
print(arr)

[[0.60885767 0.58869534 0.73736611 0.1950989 ]]


In [ ]:
#Random Array In Numpy normal distributed
arr=np.random.randn(1,4)
print(arr)

[[ 0.80745053 -0.92573509 -1.12139786  0.39328523]]


In [ ]:
#Numpy-Input to below function is (start,stop,number of elements)
arr=np.random.randint(1,10,size=4)
print(arr)

[8 5 5 8]


In [ ]:
arr=np.random.random_integers

NameError: name 'np' is not defined

In [ ]:
arr=np.array([1,2.3,3])

In [ ]:
print(arr)

[1.  2.3 3. ]


In [ ]:
lst=["priya","sneha","vaishu"]

In [ ]:
arr=np.array(lst)
print(arr)

['priya' 'sneha' 'vaishu']


In [ ]:
#Creating array with different datatypes

In [ ]:
arr=np.array([1,2,2],np.float64)
arr

array([1., 2., 2.])

In [ ]:
arr=np.array([1,2.,22],np.int64)

In [ ]:
arr

array([ 1,  2, 22])

In [ ]:
#Type casting one array to another
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr2=np.astype(arr,np.float64)

In [ ]:
arr2

array([1., 2., 3.])