<a href="https://colab.research.google.com/github/aditya-khaparde28/Python-Numpy/blob/main/numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

In [ ]:
#Random Array in Numpy Uniformly destributed
arr=np.random.rand(1,4)

In [ ]:
print(arr)

[[0.60885767 0.58869534 0.73736611 0.1950989 ]]


In [ ]:
#Random Array In Numpy normal distributed
arr=np.random.randn(1,4)
print(arr)

[[ 0.80745053 -0.92573509 -1.12139786  0.39328523]]


In [ ]:
#Numpy-Input to below function is (start,stop,number of elements)
arr=np.random.randint(1,10,size=4)
print(arr)

[8 5 5 8]


In [ ]:
arr=np.random.random_integers

NameError: name 'np' is not defined

In [ ]:
arr=np.array([1,2.3,3])

In [ ]:
print(arr)

[1.  2.3 3. ]


In [ ]:
lst=["priya","sneha","vaishu"]

In [ ]:
arr=np.array(lst)
print(arr)

['priya' 'sneha' 'vaishu']


In [ ]:
#Creating array with different datatypes

In [ ]:
arr=np.array([1,2,2],np.float64)
arr

array([1., 2., 2.])

In [ ]:
arr=np.array([1,2.,22],np.int64)

In [ ]:
arr

array([ 1,  2, 22])

In [ ]:
#Type casting one array to another
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr2=np.astype(arr,np.float64)

In [ ]:
arr2

array([1., 2., 3.])

In [ ]:
print(arr2.shape)

(3,)


In [ ]:
arr2.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Ravel is used to convert any particular array to 1D Array
arr=np.array([[1,2,2],
             [2,2,2]])

In [ ]:
arr.ravel

<function ndarray.ravel>

In [ ]:
print(arr.ravel)

<built-in method ravel of numpy.ndarray object at 0x786a0b730c30>


In [ ]:
ravel=arr.ravel()

In [ ]:
print(ravel)

[1 2 2 2 2 2]


In [ ]:
print(arr)

[[1 2 2]
 [2 2 2]]


In [ ]:
#Flatten
flatton=arr.flatten()
print(flatton)

[1 2 2 2 2 2]


In [ ]:
#Arithmetic

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([2,4,6])

In [ ]:
print(arr1+arr2)

[3 6 9]


In [ ]:
print(arr1-arr2)

[-1 -2 -3]


In [ ]:
print(arr1/arr2)

[0.5 0.5 0.5]


In [ ]:
print(arr1*arr2)

[ 2  8 18]


In [ ]:
print(arr1//arr2)

[0 0 0]


In [1]:
arr=[2,3,4]

In [2]:
arr[0,1]

TypeError: list indices must be integers or slices, not tuple

In [3]:
#Array Slice
arr[0:1]

[2]

In [5]:
arr=[2,4,6,8,20,35,66]

In [6]:
arr[1:4:2]

[4, 8]

In [13]:
#Multidimensinal Slicing
arr=np.array([[2,4,6],
     [4,7,8],
     [22,12,2]])

In [8]:
arr[0:3]

[[2, 4, 6], [4, 7, 8], [22, 12, 2]]

In [9]:
arr[0:2]

[[2, 4, 6], [4, 7, 8]]

In [10]:
arr[0:2:2]

[[2, 4, 6]]

In [14]:
#Transpose of matrix
print(arr.transpose())

[[ 2  4 22]
 [ 4  7 12]
 [ 6  8  2]]
